In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('Dataset/Train.csv')

In [3]:
dataset.head()

Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_23371      F  42.0                4             Married     Franklin   
1   EID_18000      M  24.0                3              Single  Springfield   
2    EID_3891      F  58.0                3             Married      Clinton   
3   EID_17492      F  26.0                3              Single      Lebanon   
4   EID_22534      F  31.0                1             Married  Springfield   

                        Unit Decision_skill_possess  Time_of_service  \
0                         IT             Conceptual              4.0   
1                  Logistics             Analytical              5.0   
2                    Quality             Conceptual             27.0   
3  Human Resource Management             Behavioral              4.0   
4                  Logistics             Conceptual              5.0   

   Time_since_promotion  ...  Compensation_and_Benefits  Work_Life_balance  \
0                     4  ...                      type2                3.0   
1                     4  ...                      type2                4.0   
2                     3  ...                      type2                1.0   
3                     3  ...                      type2                1.0   
4                     4  ...                      type3                3.0   

   VAR1    VAR2    VAR3  VAR4  VAR5  VAR6  VAR7  Attrition_rate  
0     4  0.7516  1.8688   2.0     4     5     3          0.1841  
1     3 -0.9612 -0.4537   2.0     3     5     3          0.0670  
2     4 -0.9612 -0.4537   3.0     3     8     3          0.0851  
3     3 -1.8176 -0.4537   NaN     3     7     3          0.0668  
4     1  0.7516 -0.4537   2.0     2     8     2          0.1827  

[5 rows x 24 columns]

In [4]:
X=dataset.drop(['Attrition_rate'],axis='columns')

In [5]:
from sklearn.preprocessing import LabelEncoder
Label=LabelEncoder()

dataset['Gender']=Label.fit_transform(dataset['Gender'])

In [6]:
X['Gender']=dataset['Gender']

In [7]:
X

Employee_ID  Gender   Age  Education_Level Relationship_Status  \
0      EID_23371       0  42.0                4             Married   
1      EID_18000       1  24.0                3              Single   
2       EID_3891       0  58.0                3             Married   
3      EID_17492       0  26.0                3              Single   
4      EID_22534       0  31.0                1             Married   
...          ...     ...   ...              ...                 ...   
6995   EID_16328       0  23.0                5             Married   
6996    EID_8387       0  44.0                1             Married   
6997    EID_8077       0  49.0                3              Single   
6998   EID_19597       0  47.0                3             Married   
6999    EID_1640       0  58.0                3             Married   

         Hometown                       Unit Decision_skill_possess  \
0        Franklin                         IT             Conceptual   
1     Springfield                  Logistics             Analytical   
2         Clinton                    Quality             Conceptual   
3         Lebanon  Human Resource Management             Behavioral   
4     Springfield                  Logistics             Conceptual   
...           ...                        ...                    ...   
6995     Franklin                 Operarions             Behavioral   
6996      Lebanon                        R&D             Analytical   
6997  Springfield                         IT              Directive   
6998   Washington                      Sales             Behavioral   
6999     Franklin                         IT              Directive   

      Time_of_service  Time_since_promotion  ...  Pay_Scale  \
0                 4.0                     4  ...        7.0   
1                 5.0                     4  ...        6.0   
2                27.0                     3  ...        8.0   
3                 4.0                     3  ...        8.0   
4                 5.0                     4  ...        2.0   
...               ...                   ...  ...        ...   
6995              4.0                     1  ...        6.0   
6996             16.0                     2  ...        4.0   
6997             10.0                     1  ...        3.0   
6998             24.0                     1  ...        8.0   
6999             22.0                     2  ...        5.0   

      Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2    VAR3  \
0                         type2                3.0     4  0.7516  1.8688   
1                         type2                4.0     3 -0.9612 -0.4537   
2                         type2                1.0     4 -0.9612 -0.4537   
3                         type2                1.0     3 -1.8176 -0.4537   
4                         type3                3.0     1  0.7516 -0.4537   
...                         ...                ...   ...     ...     ...   
6995                      type3                3.0     1  0.7516 -0.4537   
6996                      type3                3.0     2 -0.1048 -2.7762   
6997                      type2                4.0     2 -0.1048 -0.4537   
6998                      type0                2.0     4  0.7516  1.8688   
6999                      type2                3.0     3 -0.1048 -1.6150   

      VAR4  VAR5  VAR6  VAR7  
0      2.0     4     5     3  
1      2.0     3     5     3  
2      3.0     3     8     3  
3      NaN     3     7     3  
4      2.0     2     8     2  
...    ...   ...   ...   ...  
6995   2.0     3     7     3  
6996   2.0     4     8     4  
6997   2.0     4     8     3  
6998   2.0     3     6     3  
6999   3.0     4     5     3  

[7000 rows x 23 columns]

In [8]:
X['Relationship_Status']=Label.fit_transform(X['Relationship_Status'])
X['Hometown']=Label.fit_transform(X['Hometown'])
X['Unit']=Label.fit_transform(X['Unit'])
X['Decision_skill_possess']=Label.fit_transform(X['Decision_skill_possess'])
X['Compensation_and_Benefits']=Label.fit_transform(X['Compensation_and_Benefits'])

In [9]:
y=dataset['Attrition_rate']

In [10]:
X=X.fillna(X.mean())

In [11]:
X.isnull().any()

Employee_ID                  False
Gender                       False
Age                          False
Education_Level              False
Relationship_Status          False
Hometown                     False
Unit                         False
Decision_skill_possess       False
Time_of_service              False
Time_since_promotion         False
growth_rate                  False
Travel_Rate                  False
Post_Level                   False
Pay_Scale                    False
Compensation_and_Benefits    False
Work_Life_balance            False
VAR1                         False
VAR2                         False
VAR3                         False
VAR4                         False
VAR5                         False
VAR6                         False
VAR7                         False
dtype: bool

In [12]:
X

Employee_ID  Gender   Age  Education_Level  Relationship_Status  \
0      EID_23371       0  42.0                4                    0   
1      EID_18000       1  24.0                3                    1   
2       EID_3891       0  58.0                3                    0   
3      EID_17492       0  26.0                3                    1   
4      EID_22534       0  31.0                1                    0   
...          ...     ...   ...              ...                  ...   
6995   EID_16328       0  23.0                5                    0   
6996    EID_8387       0  44.0                1                    0   
6997    EID_8077       0  49.0                3                    1   
6998   EID_19597       0  47.0                3                    0   
6999    EID_1640       0  58.0                3                    0   

      Hometown  Unit  Decision_skill_possess  Time_of_service  \
0            1     2                       2              4.0   
1            3     3                       0              5.0   
2            0     8                       2             27.0   
3            2     1                       1              4.0   
4            3     3                       2              5.0   
...        ...   ...                     ...              ...   
6995         1     5                       1              4.0   
6996         2     9                       0             16.0   
6997         3     2                       3             10.0   
6998         4    10                       1             24.0   
6999         1     2                       3             22.0   

      Time_since_promotion  ...  Pay_Scale  Compensation_and_Benefits  \
0                        4  ...        7.0                          2   
1                        4  ...        6.0                          2   
2                        3  ...        8.0                          2   
3                        3  ...        8.0                          2   
4                        4  ...        2.0                          3   
...                    ...  ...        ...                        ...   
6995                     1  ...        6.0                          3   
6996                     2  ...        4.0                          3   
6997                     1  ...        3.0                          2   
6998                     1  ...        8.0                          0   
6999                     2  ...        5.0                          2   

      Work_Life_balance  VAR1    VAR2    VAR3      VAR4  VAR5  VAR6  VAR7  
0                   3.0     4  0.7516  1.8688  2.000000     4     5     3  
1                   4.0     3 -0.9612 -0.4537  2.000000     3     5     3  
2                   1.0     4 -0.9612 -0.4537  3.000000     3     8     3  
3                   1.0     3 -1.8176 -0.4537  1.891078     3     7     3  
4                   3.0     1  0.7516 -0.4537  2.000000     2     8     2  
...                 ...   ...     ...     ...       ...   ...   ...   ...  
6995                3.0     1  0.7516 -0.4537  2.000000     3     7     3  
6996                3.0     2 -0.1048 -2.7762  2.000000     4     8     4  
6997                4.0     2 -0.1048 -0.4537  2.000000     4     8     3  
6998                2.0     4  0.7516  1.8688  2.000000     3     6     3  
6999                3.0     3 -0.1048 -1.6150  3.000000     4     5     3  

[7000 rows x 23 columns]

In [13]:
X=X.drop(['Employee_ID'],axis='columns')

In [14]:
X.head()

Gender   Age  Education_Level  Relationship_Status  Hometown  Unit  \
0       0  42.0                4                    0         1     2   
1       1  24.0                3                    1         3     3   
2       0  58.0                3                    0         0     8   
3       0  26.0                3                    1         2     1   
4       0  31.0                1                    0         3     3   

   Decision_skill_possess  Time_of_service  Time_since_promotion  growth_rate  \
0                       2              4.0                     4           33   
1                       0              5.0                     4           36   
2                       2             27.0                     3           51   
3                       1              4.0                     3           56   
4                       2              5.0                     4           62   

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2  \
0  ...        7.0                          2                3.0     4  0.7516   
1  ...        6.0                          2                4.0     3 -0.9612   
2  ...        8.0                          2                1.0     4 -0.9612   
3  ...        8.0                          2                1.0     3 -1.8176   
4  ...        2.0                          3                3.0     1  0.7516   

     VAR3      VAR4  VAR5  VAR6  VAR7  
0  1.8688  2.000000     4     5     3  
1 -0.4537  2.000000     3     5     3  
2 -0.4537  3.000000     3     8     3  
3 -0.4537  1.891078     3     7     3  
4 -0.4537  2.000000     2     8     2  

[5 rows x 22 columns]

In [15]:
y

0       0.1841
1       0.0670
2       0.0851
3       0.0668
4       0.1827
         ...  
6995    0.7839
6996    0.1055
6997    0.7847
6998    0.4162
6999    0.0910
Name: Attrition_rate, Length: 7000, dtype: float64

In [16]:
len(X.columns)

22

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
scaled_data=scaler.transform(X)

In [19]:
scaled_data

array([[-0.83756018,  0.18009898,  0.76255659, ...,  1.24175608,
        -1.80495079, -0.27776175],
       [ 1.19394406, -1.18359795, -0.17638732, ...,  0.17665468,
        -1.80495079, -0.27776175],
       [-0.83756018,  1.39227403, -0.17638732, ...,  0.17665468,
         0.77197263, -0.27776175],
       ...,
       [-0.83756018,  0.71042557, -0.17638732, ...,  1.24175608,
         0.77197263, -0.27776175],
       [-0.83756018,  0.55890369, -0.17638732, ...,  0.17665468,
        -0.94597631, -0.27776175],
       [-0.83756018,  1.39227403, -0.17638732, ...,  1.24175608,
        -1.80495079, -0.27776175]])

In [20]:
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
pca.fit(scaled_data)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [21]:
x_pca=pca.transform(scaled_data)

In [22]:
print(x_pca.shape)
scaled_data.shape

(7000, 10)


(7000, 22)

In [23]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()

linear_model.fit(x_pca,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
linear_model.intercept_

0.18937612857142858

In [25]:
from sklearn.tree import DecisionTreeRegressor
tree_model=DecisionTreeRegressor()

tree_model.fit(x_pca,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [26]:
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor()

knn_model.fit(x_pca,y)


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [27]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor()

rf_model.fit(x_pca,y)

C:\Users\abhijeet\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [28]:
from sklearn.svm import SVR
sv_model=SVR(kernel='rbf')

sv_model.fit(x_pca,y)


C:\Users\abhijeet\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [43]:
import xgboost as xgb

xg_model = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

xg_model.fit(x_pca,y)

[09:19:18] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[09:19:18] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.3, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=5,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=10, n_jobs=0, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=10, reg_lambda=1,
             scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [31]:
test_data=pd.read_csv('Dataset/test.csv')

In [32]:
test_data.head()

Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_22713      F  32.0                5              Single  Springfield   
1    EID_9658      M  65.0                2              Single      Lebanon   
2   EID_22203      M  52.0                3             Married  Springfield   
3    EID_7652      M  50.0                5              Single   Washington   
4    EID_6516      F  44.0                3             Married     Franklin   

        Unit Decision_skill_possess  Time_of_service  Time_since_promotion  \
0        R&D             Conceptual              7.0                     4   
1         IT              Directive             41.0                     2   
2      Sales              Directive             21.0                     3   
3  Marketing             Analytical             11.0                     4   
4        R&D             Conceptual             12.0                     4   

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2  \
0  ...        4.0                      type2                1.0     3 -0.9612   
1  ...        1.0                      type2                1.0     4 -0.9612   
2  ...        8.0                      type3                1.0     4 -0.1048   
3  ...        2.0                      type0                4.0     3 -0.1048   
4  ...        2.0                      type2                4.0     4  1.6081   

     VAR3  VAR4  VAR5  VAR6  VAR7  
0 -0.4537   2.0     1     8     4  
1  0.7075   1.0     2     8     2  
2  0.7075   2.0     1     9     3  
3  0.7075   2.0     2     8     3  
4  0.7075   2.0     2     7     4  

[5 rows x 23 columns]

In [33]:
test_data=test_data.drop(['Employee_ID'],axis='columns')

from sklearn.preprocessing import LabelEncoder
Label=LabelEncoder()

test_data['Gender']=Label.fit_transform(test_data['Gender'])
test_data['Relationship_Status']=Label.fit_transform(test_data['Relationship_Status'])

test_data['Hometown']=Label.fit_transform(test_data['Hometown'])
test_data['Unit']=Label.fit_transform(test_data['Unit'])

test_data['Decision_skill_possess']=Label.fit_transform(test_data['Decision_skill_possess'])
test_data['Compensation_and_Benefits']=Label.fit_transform(test_data['Compensation_and_Benefits'])

test_data=test_data.fillna(test_data.mean())

In [34]:
test_data.head()

Gender   Age  Education_Level  Relationship_Status  Hometown  Unit  \
0       0  32.0                5                    1         3     9   
1       1  65.0                2                    1         2     2   
2       1  52.0                3                    0         3    10   
3       1  50.0                5                    1         4     4   
4       0  44.0                3                    0         1     9   

   Decision_skill_possess  Time_of_service  Time_since_promotion  growth_rate  \
0                       2              7.0                     4           30   
1                       3             41.0                     2           72   
2                       3             21.0                     3           25   
3                       0             11.0                     4           28   
4                       2             12.0                     4           47   

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2  \
0  ...        4.0                          2                1.0     3 -0.9612   
1  ...        1.0                          2                1.0     4 -0.9612   
2  ...        8.0                          3                1.0     4 -0.1048   
3  ...        2.0                          0                4.0     3 -0.1048   
4  ...        2.0                          2                4.0     4  1.6081   

     VAR3  VAR4  VAR5  VAR6  VAR7  
0 -0.4537   2.0     1     8     4  
1  0.7075   1.0     2     8     2  
2  0.7075   2.0     1     9     3  
3  0.7075   2.0     2     8     3  
4  0.7075   2.0     2     7     4  

[5 rows x 22 columns]

In [35]:
test_data=scaler.transform(test_data)

array([[-0.83756018, -0.57751043,  1.70150049, ..., -1.95354814,
         0.77197263,  0.80302326],
       [ 1.19394406,  1.92260062, -1.11533123, ..., -0.88844673,
         0.77197263, -1.35854675],
       [ 1.19394406,  0.93770839, -0.17638732, ..., -1.95354814,
         1.6309471 , -0.27776175],
       ...,
       [-0.83756018,  1.54379592,  0.76255659, ...,  1.24175608,
         0.77197263,  0.80302326],
       [-0.83756018,  0.86194745, -2.05427513, ...,  0.17665468,
         1.6309471 , -1.35854675],
       [-0.83756018,  0.4073818 , -2.05427513, ..., -0.88844673,
         0.77197263,  1.88380826]])

In [36]:
test_pca=pca.transform(test_data)

In [37]:
test_pca

array([[ 27.90980945, -13.48229494,   3.39511714, ...,  -0.30112161,
          6.24392877,  -4.78469055],
       [ 73.87338509, -21.91687112,  22.82161414, ...,   4.98666101,
         16.31165391,  -0.53813494],
       [ 51.33715162, -11.64321392,   1.84006506, ...,   1.24532823,
          6.62023206,  -3.4292402 ],
       ...,
       [ 66.08263796, -21.95065297,  16.38386619, ...,   3.41189924,
         17.4225754 ,  -1.98792884],
       [ 51.53784249, -10.98052419,   5.52264155, ...,   1.85431703,
          7.13160772,  -3.20506049],
       [ 40.62107508, -23.09140075,  17.90052203, ...,   7.17135926,
         15.55579099,  -5.64696459]])

In [38]:
test1=linear_model.predict(test_pca)
test1

array([0.1085704 , 0.03916306, 0.06411808, ..., 0.02695776, 0.03963159,
       0.08618537])

In [39]:
test2=tree_model.predict(test_pca)
test2

array([0.0278, 0.1729, 0.42  , ..., 0.58  , 0.6516, 0.9957])

In [40]:
test3=knn_model.predict(test_pca)
test3

array([0.15234, 0.31482, 0.27854, ..., 0.27924, 0.2665 , 0.20884])

In [41]:
test4=rf_model.predict(test_pca)
test4

array([0.5861 , 0.43115, 0.43265, ..., 0.28466, 0.43134, 0.56774])

In [42]:
test5=sv_model.predict(test_pca)
test5

array([0.22078225, 0.22078225, 0.22078225, ..., 0.22078225, 0.22078225,
       0.22078225])

In [44]:
test6=xg_model.predict(test_pca)
test6

array([0.36616245, 0.40454018, 0.36616245, ..., 0.36616245, 0.36616245,
       0.40454018], dtype=float32)

In [45]:
d=pd.read_csv('Dataset/test.csv')

In [47]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test1}
df=pd.DataFrame(data=df)

df.to_csv('results1.csv')
df


Employee_ID  Attrition_rate
0      EID_22713        0.108570
1       EID_9658        0.039163
2      EID_22203        0.064118
3       EID_7652        0.079096
4       EID_6516        0.089729
...          ...             ...
2995   EID_22547        0.128162
2996   EID_10066        0.076528
2997    EID_7126        0.026958
2998    EID_4929        0.039632
2999   EID_24750        0.086185

[3000 rows x 2 columns]

In [48]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test2}
df=pd.DataFrame(data=df)

df.to_csv('results2.csv')
df


Employee_ID  Attrition_rate
0      EID_22713          0.0278
1       EID_9658          0.1729
2      EID_22203          0.4200
3       EID_7652          0.1908
4       EID_6516          0.9957
...          ...             ...
2995   EID_22547          0.9957
2996   EID_10066          0.0478
2997    EID_7126          0.5800
2998    EID_4929          0.6516
2999   EID_24750          0.9957

[3000 rows x 2 columns]

In [49]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test3}
df=pd.DataFrame(data=df)

df.to_csv('results3.csv')
df


Employee_ID  Attrition_rate
0      EID_22713         0.15234
1       EID_9658         0.31482
2      EID_22203         0.27854
3       EID_7652         0.32614
4       EID_6516         0.31906
...          ...             ...
2995   EID_22547         0.18646
2996   EID_10066         0.28588
2997    EID_7126         0.27924
2998    EID_4929         0.26650
2999   EID_24750         0.20884

[3000 rows x 2 columns]

In [50]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test4}
df=pd.DataFrame(data=df)

df.to_csv('results4.csv')
df


Employee_ID  Attrition_rate
0      EID_22713         0.58610
1       EID_9658         0.43115
2      EID_22203         0.43265
3       EID_7652         0.46417
4       EID_6516         0.48930
...          ...             ...
2995   EID_22547         0.56774
2996   EID_10066         0.35029
2997    EID_7126         0.28466
2998    EID_4929         0.43134
2999   EID_24750         0.56774

[3000 rows x 2 columns]

In [51]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test5}
df=pd.DataFrame(data=df)

df.to_csv('results5.csv')
df


Employee_ID  Attrition_rate
0      EID_22713        0.220782
1       EID_9658        0.220782
2      EID_22203        0.220782
3       EID_7652        0.220782
4       EID_6516        0.220782
...          ...             ...
2995   EID_22547        0.220782
2996   EID_10066        0.220782
2997    EID_7126        0.220782
2998    EID_4929        0.220782
2999   EID_24750        0.220782

[3000 rows x 2 columns]

In [52]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test6}
df=pd.DataFrame(data=df)

df.to_csv('results6.csv')
df


Employee_ID  Attrition_rate
0      EID_22713        0.366162
1       EID_9658        0.404540
2      EID_22203        0.366162
3       EID_7652        0.366162
4       EID_6516        0.366162
...          ...             ...
2995   EID_22547        0.366162
2996   EID_10066        0.404540
2997    EID_7126        0.366162
2998    EID_4929        0.366162
2999   EID_24750        0.404540

[3000 rows x 2 columns]

In [54]:
from sklearn.linear_model import Lasso
Lasso_model=Lasso()

Lasso_model.fit(x_pca,y)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [55]:
test7=Lasso_model.predict(test_pca)

In [56]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test7}
df=pd.DataFrame(data=df)

df.to_csv('results7.csv')
df


Employee_ID  Attrition_rate
0      EID_22713        0.189376
1       EID_9658        0.189376
2      EID_22203        0.189376
3       EID_7652        0.189376
4       EID_6516        0.189376
...          ...             ...
2995   EID_22547        0.189376
2996   EID_10066        0.189376
2997    EID_7126        0.189376
2998    EID_4929        0.189376
2999   EID_24750        0.189376

[3000 rows x 2 columns]

In [58]:
from sklearn.linear_model import Ridge
Ridge_model=Ridge(alpha=0.05,normalize=True)

Ridge_model.fit(x_pca,y)


Ridge(alpha=0.05, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=True, random_state=None, solver='auto', tol=0.001)

In [59]:
test8=Ridge_model.predict(test_pca)

In [60]:
df={'Employee_ID':d['Employee_ID'],'Attrition_rate':test8}
df=pd.DataFrame(data=df)

df.to_csv('results8.csv')
df


Employee_ID  Attrition_rate
0      EID_22713        0.112418
1       EID_9658        0.046315
2      EID_22203        0.070082
3       EID_7652        0.084347
4       EID_6516        0.094473
...          ...             ...
2995   EID_22547        0.131076
2996   EID_10066        0.081901
2997    EID_7126        0.034691
2998    EID_4929        0.046762
2999   EID_24750        0.091098

[3000 rows x 2 columns]